### ISSUE TITLE
zcage pull - escaped string error

### ISSUE THREAD

**Issue by MarkProminic** [cneira/zcage#44]
Hello, When I try to pull CentOS-7 from Cloudinit I get this error:

root@HV-02:/tmp# zcage pull  --image CentOS-7-x86_64-GenericCloud-1511.qcow2c.xz --provider cloud-init centos/6
/root/zcage/lib/imgadm.js:268
        output = ZCAGE.IMAGES + '/' + resp.req.path.split('/').pop();
                                      ^

ReferenceError: resp is not defined
    at fetch (/root/zcage/lib/imgadm.js:268:39)
    at Object.fetch_by_provider (/root/zcage/lib/imgadm.js:342:5)
    at Object.<anonymous> (/root/zcage/zcage:448:25)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:74:12)
    at internal/main/run_main_module.js:18:47

I notice that the script doesn't error out when I pass two // IE: 

zcage pull  --image CentOS-7-x86_64-GenericCloud-1511.qcow2c.xz --provider cloud-init centos//7
but, then I get: 

Distro not supported

I tested other zcage pull mechanisms like docker and joyent and they downloaded without issue. 

I have other manually installed bhyve installations, but I can't get the images to pull.

**Comment by cneira** [comment]
@MarkProminic 
thanks for the bug report I'll take a look now.

**Comment by cneira** [comment]
This should be fixed by https://github.com/cneira/zcage/commit/5558c75148a5175db4556e1398aba57ab480b44f
Feel free to reopen if the issue persists.
