### ISSUE TITLE
Docker image - TypeError: Cannot read property 'Env' of undefined

### ISSUE THREAD

**Issue by DieterTHeck** [cneira/zcage#50]
Hi,

zcage is running fine on Omnios r151034m and works fine with Docker images, e.g. alpine latest or plex (plexinc/pms-docker latest).

I have issues with openhab, see below.

zcage create --alias=openhab_test --net "vnet0|xxx|xxx" --ram 2gb --docker openhab/openhab latest --brand lx

openhab_test created [OK]
/root/zcage/lib/zone.js:3372
    env = obj.Env.join(' ');
              ^
TypeError: Cannot read property 'Env' of undefined
    at addtr_from_docker_img (/root/zcage/lib/zone.js:3372:15)
    at Request._callback (/root/zcage/lib/imgadm.js:965:21)
    at Request.self.callback (/root/zcage/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/root/zcage/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/root/zcage/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)

**Comment by cneira** [comment]
I'll need a couple of days to take a look at this one.

**Comment by cneira** [comment]
@DieterTHeck 
This should be fixed in master now.
